### ISSUE TITLE
Mode for consecutive programs

### ISSUE THREAD

**Issue by ai-alanov** [ferrine/gpu-batch.sub#1]
It will be great if there is an argument which says that the programs should be run consecutively.

**Comment by ferrine** [comment]
Hi! It is a nice suggestion. I'm afraid it has corner cases when you want to do something like this
```
job1->job2
job3->job4
job5->job6
```
so pairs of jobs run in parallel within one bsub submit.

One approach I see to cover this additional case is to add special syntax for files, eg

```
<separator>
job1
job2
<separator>
job3
job4
<separator>
```
or

```
job1
job2
<separator>
job3
job4
<separator>
job5
job6
```

**Comment by ferrine** [comment]
A flag can only indicate all jobs are sequential

**Comment by ferrine** [comment]
Considering current implementation, the following syntax will be easier to implement
```
<begin>
job1
job2
<end>
<begin>
job3
job4
<end>
```
How do you feel about it?

**Comment by ai-alanov** [comment]
Yes, I think it will fit my needs.

**Comment by ferrine** [comment]
Closed by https://github.com/ferrine/gpu-batch.sub/pull/2
